### ISSUE TITLE
There are no assets folder.

### ISSUE THREAD

**Issue by Wraient** [DipanshuAmbilkar03/spotify_clone_01#2]
My dear dipu,
You have uploaded 2 files, which are html and css files but you have uploaded 2 additional files which has no purpose in life other than to just take space on your as well as github's storage. I suggest you kys and try to get better. Noob.

P.S. There are no assets folder just like your skills.

**Comment by DipanshuAmbilkar03** [comment]
Certainly, not adding assets is my mistake.
But the remaining 2 file do have some relevance because this project is not complete yet.

**Comment by DipanshuAmbilkar03** [comment]
BTW have a look on readme.md.>_<

**Comment by Wraient** [comment]
Indeed, it was my mistake to doubt on your skills but perhaps some changes are in order to restructure this repository to not upload various empty files without any apparent reason this could cause user confusion. I am extremely sorry for my foul language and my apologies sincerely from bottom of my heart <3

Hope you find it in your unlimited highness to forgive me.

Also,
Your readme.md sounds very generative. UwU.

Btw I use arch.

**Comment by Wraient** [comment]
Due to no reply from your side in last 1 week I have came to the conclusion that you don't have any interest in maintaining this project anymore, and I would like to withdraw trying to make the repo better.

Thanks for replying.
Bye.
